spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-160-18-230.compute-1.amazonaws.com:5432/deckdu758f9bak?user=yeyroobovxbnhd&password=3cb128e48e19bab8efd1b2b4dd9a9b2678ebb40768f700059241d73bde4aa271&sslmode=require
